plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = mod_version
group = maven_group

base {
    archivesName = archives_base_name
}

repositories {
    // Fabric & Minecraft repos are added automatically by Loom
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"

    // Fabric API (required for client commands)
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

processResources {
    inputs.property "version", version

    filesMatching("fabric.mod.json") {
        expand version: version
    }
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

jar {
    from("LICENSE") {
        rename { "${it}_${archives_base_name}" }
    }
}
